---
- name: sshd role
  tags:
    - sshd
  block:

  # sshd_config
  - when: sshd_config != None
    name: Copy {{ sshd_config }}
    become: true
    notify: Reload ssh.service
    ansible.builtin.copy:
      src: "{{ sshd_config }}"
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: "u=rw,g=,o="