---
- name: Restart ssh.service
  when: sshd_handler_restart == true
  become: true
  ansible.builtin.service:
    name: ssh.service
    state: restarted

- name: Reload ssh.service
  when: sshd_handler_reload == true
  become: true
  ansible.builtin.service:
    name: ssh.service
    state: reloaded